apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-service
  labels:
    app: coffee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-service
  template:
    metadata:
      labels:
        app: coffee-service
    spec:
      containers:
      - name: coffee-service
        image:  gcr.io/siva-gke/coffee-service:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent