apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-service
  labels:
    app: coffee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-service
  template:
    metadata:
      labels:
        app: coffee-service
    spec:
      containers:
      - name: coffee-service
        image: coffee-service:latest
        env: 
          - name: MONGO_USER
            value: root
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongodb-root-password
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent