kind: Service
apiVersion: v1
metadata:
  name: coffee-service
  labels:
    app: coffee-service
spec:
  selector:
    app: coffee-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
