kind: Service
apiVersion: v1
metadata:
  name: python-service
  labels:
    app: python-service
spec:
  selector:
    app: python-service
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: NodePort
